Algoritmo "Exercício 3 - j"
// 
//  
// Descrição   : Escreve se o valor está entre 1 e 9 ou não.
// Autor(a)    : Pedro H. Costa
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
   valor: Inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um valor: ")
   leia(valor)
   
   se (valor % = 0) entao
      escreva("Esse valor é PAR")
   senao
        escreva("Esse valor é IMPAR")
   fimse


Fimalgoritmo