Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/04/2022
Var
// Seção de Declarações das variáveis 
   cont, result: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   cont <- 1
   enquanto (cont <= 100)faca
       result <- result + cont
       escreval("A soma é: ", result)
       cont <- cont + 1
   
   
   fimenquanto


Fimalgoritmo