Algoritmo "Laço de Repetição"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pedro H. Costa
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
   contador: Inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contador <= 12 faca
             escreval(contador, " - Pedro")
             contador <- contador + 1
   fimenquanto


Fimalgoritmo