Algoritmo "Valor ao quadrado"
//  
//  
// 
//  
// Descrição   : Recebe um valor inteiro e calcula ele ao quadrado
// Autor(a)    : Pedro H. Costa
// Data atual  : 22/03/2022
Var
// Seção de Declarações das variáveis 
   valor, quadrado: Real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(valor)
   
   quadrado <- valor * valor
   
   escreva(valor, "²(ao quadrado):", quadrado)


Fimalgoritmo