Algoritmo "Exercicio 15"
// 
//  
// Descrição   : Descobre se um valor é impar ou par
// Autor(a)    : Pedro H. Costa
// Data atual  : 23/03/2022
Var
// Seção de Declarações das variáveis 
   valor:Real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um valor: ")
   leia(valor)
   
   se (valor % 2 = 0)entao
      escreva("Esse numero é PAR")
   senao
      escreva("Esse numero é IMPAR")
   fimse
   


Fimalgoritmo