Algoritmo "Soma"
// 
//  
// Descrição   : App de soma
// Autor(a)    :  Pedro H.costa
// Data atual  : 16/03/2022
Var
// Seção de Declarações das variáveis 
 gaveta1, gaveta2, soma: inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um valor: ")
   leia(gaveta1)
   Escreva("Digite outro valor: ")
   leia(gaveta2)
   soma <- gaveta1 + gaveta2
   escreva("O valor da soma é: ", soma)


Fimalgoritmo