Algoritmo "Exercicio 23"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/03/2022
Var
// Seção de Declarações das variáveis 
   altura, peso_ideal: Real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite sua altura (em metros ex 1.8): ")
   leia(altura)
   
   escreva("Informe seu sexo: Femino[1 ")
   leia

   
   
   
   
   
   




Fimalgoritmo