Algoritmo "De Real para Dolar"
// 
//  
// Descrição   : Converte um valor em real para Dolar.
// Autor(a)    : Pedro H. Costa
// Data atual  : 22/03/2022
Var
// Seção de Declarações das variáveis
   a, b, c, soma: Inteiro
 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Primeiro valor: ")
   leia(a)
   
   escreva("Segundo valor: ")
   leia(b)
   
   escreva("Terceiro valor: ")
   leia(c)
   

   
   


Fimalgoritmo